location/urls.py
from django.urls import path

from location import views

app_name = 'location'

urlpatterns = [
    path('', views.LocationView.as_view(), name='lista_locatii'),
    path('adaugare/', views.CreateLocationView.as_view(), name='adaugare'),
    path('<int:pk>/update/', views.UpdateLocationView.as_view(), name="modificare"),

    path('<int:pk>/delete/', views.delete_location, name='stergere'),
    path('<int:pk>/activate/', views.activate_location, name='activare'),
]

proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('location/', include('location.urls')),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('user_profile/', include('userprofile.urls')),

]

templates/userprofile/urls.py
from django.urls import path

from userprofile import views

app_name = 'userprofile'

urlpatterns = [
    path('new_account/', views.CreateNewAccount.as_view(), name='utilizator_nou'),
]

userprofile/urls.py
from django.urls import path

from userprofile import views

app_name = 'userprofile'

urlpatterns = [
    path('new_account/', views.CreateNewAccount.as_view(), name='utilizator_nou'),
]

location/models.py
from django.db import models


class Location(models.Model):

    city = models.CharField(max_length=100)
    country = models.CharField(max_length=90)
    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.city} -> {self.country}"


class Log(models.Model):

    action_choices = (('created', 'created'),
                      ('updated', 'updated'),
                      ('refresh', 'refresh'))
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    action = models.CharField(max_length=10, choices=action_choices)
    url = models.CharField(max_length=100)

userprofile/models.py
from django.db import models

# Create your models here.

userprofile/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import TextInput


class NewAccountForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username']

        widgets = {
            'first_name': TextInput(attrs={'placeholder': 'first_name', 'class': 'form-control'}),
            'last_name': TextInput(attrs={'placeholder': 'last_name', 'class': 'form-control'}),
            'email': TextInput(attrs={'placeholder': 'email', 'class': 'form-control'}),
            'username': TextInput(attrs={'placeholder': 'username', 'class': 'form-control'})
        }

    def clean(self):
        field_data = self.cleaned_data
        email_value = field_data.get('email')
        username_value = field_data.get('username')

        if User.objects.filter(email=email_value).exists():
            msg = 'Emailul deja exista, te rugam sa adaugi alt mail'
            self._errors['email'] = self.error_class([msg])

        if User.objects.filter(username=username_value).exists():
            msg_username = 'Username deja exista, te rugam sa adaugi altul'
            self._errors['username'] = self.error_class([msg_username])
        return field_data

location/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from location.models import Location


# Create your views here.

class LocationView(LoginRequiredMixin, ListView):
    model = Location
    template_name = 'location/location_index.html'


class CreateLocationView(LoginRequiredMixin, CreateView):
    model = Location
    fields = ['city', 'country']
    template_name = 'location/location_form.html'

    def get_success_url(self):
        return reverse('location:lista_locatii')

class UpdateLocationView(LoginRequiredMixin, UpdateView):
    model = Location
    fields = ['city', 'country']
    template_name = 'location/location_form.html'

    def get_success_url(self):
        return reverse('location:lista_locatii')


@login_required
def delete_location(request, pk):
    Location.objects.filter(id=pk).update(active=0)
    return redirect('location:lista_locatii')


@login_required
def activate_location(request, pk):
    Location.objects.filter(id=pk).update(active=1)
    return redirect('location:lista_locatii')

templates/userprofile/views.py
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.views.generic import CreateView

from userprofile.forms import NewAccountForm
import random
import string


class CreateNewAccount(LoginRequiredMixin, CreateView):
    model = User
    template_name = 'location/location_form.html'
    form_class = NewAccountForm

    def get_success_url(self):
        psw = ''.join(
            random.SystemRandom().choice(string.ascii_uppercase + string.ascii_lowercase + string.digits + '$%^&') for _
            in range(8))

        if (user_instance := User.objects.filter(id=self.object.id)) and user_instance.exists():
            user_object = user_instance.first()
            user_object.set_password(psw)
            user_object.save()

            content1 = f'Buna ziua.\n Datele de aut sunt: \n username: {user_object.username} \nparola: {psw}'
            msg_html = render_to_string('registration/invite_user.html', {'content_email': content1})

            email = EmailMultiAlternatives(subject='Date contact platforma',
                                           body=content1,
                                           from_email='contact@jobs',
                                           to=[user_object.email()])
            email.attach_alternatives(msg_html, 'text/html')
            email.send()

        return reversed('location:lista_locatii')

userprofile/views.py
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.generic import CreateView

from userprofile.forms import NewAccountForm
import random
import string


class CreateNewAccount(LoginRequiredMixin, CreateView):
    model = User
    template_name = 'location/location_form.html'
    form_class = NewAccountForm

    def get_success_url(self):
        psw = ''.join(
            random.SystemRandom().choice(string.ascii_uppercase + string.ascii_lowercase + string.digits + '$%^&') for _
            in range(8))

        if (user_instance := User.objects.filter(id=self.object.id)) and user_instance.exists():
            user_object = user_instance.first()
            user_object.set_password(psw)
            user_object.save()

            content1 = f'Buna ziua.\n Datele de aut sunt: \n username: {user_object.username} \nparola: {psw}'
            msg_html = render_to_string('registration/invite_user.html', {'content_email': content1})

            email = EmailMultiAlternatives(subject='Date contact platforma',
                                           body=content1,
                                           from_email='contact@jobs',
                                           to=[user_object.email])
            email.attach_alternative(msg_html, 'text/html')
            email.send()

        return reverse('location:lista_locatii')

templates/base.html
<html>
<head>
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav>
                {% if request.user.is_authenticated %}
                    <a class="btn btn-info" href="{% url 'location:lista_locatii' %}">Locatii de vacanta</a>
                    <a href="{% url 'userprofile:utilizator_nou' %}" class="btn btn-primary">Cont nou</a>
                    <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
                {% endif %}
            </nav>
        </div>
    </div>
</div>
{% block content %}
{% endblock %}
</body>
</html>

templates/location/location_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }} {{ field.errors }} <br>
        {% endfor %}
        <button type="submit" class="btn btn-danger">Salveaza</button>
    </form>
{% endblock %}

templates/location/location_index.html
{% extends 'base.html' %}
{% block content %}
    <a class="btn btn-primary" href="{% url 'location:adaugare' %}">Adaugare locatii</a>
    <table class="table">
        <thead>
        <tr>
            <th>Index</th>
            <th>Oras</th>
            <th>Tara</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        {% for item in location_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.city }}</td>
                <td>{{ item.country }}</td>
                <td>
                    {% if item.active %}
                    Vizitat
                    {% else %}
                    Nevizitat
                    {% endif %}
                <td>
                    <a class="btn btn-success" href="{% url 'location:modificare' item.id %}">Editare locatie</a>
                    {% if item.active %}
                        <a class="btn btn-warning" href="{% url 'location:stergere' item.id %}">Stergere</a>
                    {% else %}
                        <a class="btn btn-warning" href="{% url 'location:activare' item.id %}">Marcheaza drept locatie vizitata</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}